version: "3"
services:
  emt-db-orders:
    image: "postgres"
    container_name: "po_orders"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=po_orders
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-orders:/var/lib/postgresql/data
  emt-db-items:
    image: "postgres"
    container_name: "po_items"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=po_items
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-items:/var/lib/postgresql/data

volumes:
  postgres-data-orders:
  postgres-data-items: